import type { Metadata } from "next";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";


export const metadata: Metadata = {
  title: "Builder - Artify",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <SidebarProvider >
    //   <AppSidebar />
    <main className="min-w-[80%]">
      {/* <SidebarTrigger /> */}
      {children}
    </main>
    // </SidebarProvider>
  );
}
